# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0008_auto_20160321_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kateterolayi',
            name='takildigi_merkez',
            field=models.CharField(choices=[('d', 'Devlet Hastanesi'), ('a', 'Araştırma Hastanesi'), ('u', 'Üniversite Hastanesi'), ('o', 'Özel Hastane')], default='a', max_length=1, verbose_name='Takıldığı/açıldığı merkez'),
        ),
        migrations.AlterField(
            model_name='kateterolayi',
            name='takilma_tarihi',
            field=models.DateField(verbose_name='Takılma/Açılma tarihi'),
        ),
    ]
