# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antibiyogram', '0001_initial'),
        ('hasta', '0009_auto_20160323_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiyalizOlayi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='değiştirilme tarihi')),
                ('isi_hiperemi_puy', models.BooleanField(default=False, verbose_name='FİSTÜL/KATETER BÖLGESİNSE ISI ARTIŞI/HİPEREMİ/PÜY VARLIĞI')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta.Hasta')),
                ('kateter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta.KateterOlayi')),
            ],
        ),
        migrations.CreateModel(
            name='Duyarlilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direnc', models.CharField(choices=[('d', 'Duyarli'), ('o', 'Orta Duyarlı'), ('r', 'Dirençli')], max_length=1, verbose_name='Direnç')),
                ('antibiyotik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antibiyogram.Antibiyotik')),
            ],
        ),
        migrations.CreateModel(
            name='Etken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mikroorganizma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antibiyogram.Mikroorganizma')),
                ('olay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta.DiyalizOlayi')),
            ],
        ),
        migrations.AddField(
            model_name='duyarlilik',
            name='etken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta.Etken'),
        ),
    ]
