# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0010_auto_20160324_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyalizolayi',
            name='iv_antibiyotik',
            field=models.BooleanField(default=False, verbose_name='IV ANTİBİYOTİK TEDAVİSİ'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='kan_kulturunde_ureme',
            field=models.BooleanField(default=False, verbose_name='KAN KÜLTÜRÜNDE ÜREME'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='olay_tarihi',
            field=models.DateField(default=datetime.datetime(2016, 3, 28, 21, 11, 35, 547918, tzinfo=utc), verbose_name='Olay tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duyarlilik',
            name='direnc',
            field=models.CharField(blank=True, choices=[('', 'Bakılmadı'), ('d', 'Duyarli'), ('o', 'Orta Duyarlı'), ('r', 'Dirençli')], max_length=1, verbose_name='Direnç'),
        ),
    ]
