# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0012_auto_20160329_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyalizolayi',
            name='etken_alindi_mi',
            field=models.BooleanField(default=False, verbose_name='Etken alındı mı'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='kateterde_ureme',
            field=models.BooleanField(default=False, verbose_name='Kateterde üreme'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='olasi_kaynak',
            field=models.CharField(choices=[('v', 'Vasküler giriş'), ('vh', 'Vasküler giriş harici'), ('k', 'Kontaminasyon'), ('b', 'Belirsiz')], default='b', max_length=2, verbose_name='Pozitif kan kültürünün olası kaynağı'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='periferde_ureme',
            field=models.BooleanField(default=False, verbose_name='Periferde üreme'),
        ),
    ]
