# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0013_auto_20160330_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diyalizolayi',
            name='etken_alindi_mi',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır')], default='h', max_length=1, verbose_name='Etken alindi mı?'),
        ),
    ]
