# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0014_auto_20160330_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyalizolayi',
            name='acik_yara',
            field=models.BooleanField(default=False, verbose_name='Kateter / Fistül girişi dışında bir bölgede açık yara'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='ates',
            field=models.BooleanField(default=False, verbose_name='Ateş'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='diger',
            field=models.BooleanField(default=False, verbose_name='Diğer'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='hipotansiyon',
            field=models.BooleanField(default=False, verbose_name='Hipotansiyon (TA< 120/80)'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='hospitalizasyon',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilinmiyor')], default='b', max_length=1, verbose_name='Hospitalizasyon'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='kateter_cikarildi',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilinmiyor')], default='b', max_length=1, verbose_name='Kateter çıkarıldı'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='olum',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilinmiyor')], default='b', max_length=1, verbose_name='Ölüm'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='pnomoni_sye',
            field=models.BooleanField(default=False, verbose_name='Pnömoni/ solunum yolu enfeksiyonu'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='selulit',
            field=models.BooleanField(default=False, verbose_name='Kateter/Fistül girişi dışında bir bölgede selülit'),
        ),
        migrations.AddField(
            model_name='diyalizolayi',
            name='uriner_enfeksiyon',
            field=models.BooleanField(default=False, verbose_name='Üriner enfeksiyon'),
        ),
        migrations.AlterField(
            model_name='diyalizolayi',
            name='etken_alindi_mi',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır')], default='h', max_length=1, verbose_name='Etken alındı mı?'),
        ),
    ]
