# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0015_auto_20160331_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasta',
            name='n_AntiHBcIgG',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='AntiHBcIgG'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='n_AntiHBcIgM',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='AntiHBcIgM'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='n_AntiHBs',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='AntiHBs'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='n_AntiHCV',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='AntiHCV'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='n_AntiHIV',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='AntiHIV'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='n_HBsAg',
            field=models.CharField(choices=[('p', 'Pozitif'), ('n', 'Negatif'), ('b', 'Bakılmadı')], default='b', max_length=1, verbose_name='HBsAg'),
        ),
    ]
