# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:22
from __future__ import unicode_literals

from django.db import migrations

def transfer_seroloji(apps, schema_editor):
    Hasta = apps.get_model("hasta", "Hasta")
    field_list = ['HBsAg', 'AntiHBs', 'AntiHBcIgG', 'AntiHBcIgM', 'AntiHCV', 'AntiHIV']
    for hasta in Hasta.objects.all():
        for fieldname in field_list:
            n_fieldname = 'n_' + fieldname
            old_val = getattr(hasta,fieldname)
            if old_val:
                setattr(hasta,n_fieldname,'p')
            else:
                setattr(hasta,n_fieldname,'n')
        hasta.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0016_auto_20160401_2021'),
    ]

    operations = [
        migrations.RunPython(transfer_seroloji),
    ]
