# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0017_auto_20160401_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasta',
            name='AntiHBcIgG',
        ),
        migrations.RemoveField(
            model_name='hasta',
            name='AntiHBcIgM',
        ),
        migrations.RemoveField(
            model_name='hasta',
            name='AntiHBs',
        ),
        migrations.RemoveField(
            model_name='hasta',
            name='AntiHCV',
        ),
        migrations.RemoveField(
            model_name='hasta',
            name='AntiHIV',
        ),
        migrations.RemoveField(
            model_name='hasta',
            name='HBsAg',
        ),
    ]
