# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0018_auto_20160401_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasta',
            old_name='n_AntiHBcIgG',
            new_name='AntiHBcIgG',
        ),
        migrations.RenameField(
            model_name='hasta',
            old_name='n_AntiHBcIgM',
            new_name='AntiHBcIgM',
        ),
        migrations.RenameField(
            model_name='hasta',
            old_name='n_AntiHBs',
            new_name='AntiHBs',
        ),
        migrations.RenameField(
            model_name='hasta',
            old_name='n_AntiHCV',
            new_name='AntiHCV',
        ),
        migrations.RenameField(
            model_name='hasta',
            old_name='n_AntiHIV',
            new_name='AntiHIV',
        ),
        migrations.RenameField(
            model_name='hasta',
            old_name='n_HBsAg',
            new_name='HBsAg',
        ),
    ]
