# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0021_auto_20160401_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasta',
            name='idiopatik',
            field=models.BooleanField(default=False, verbose_name='İdiopatik'),
        ),
        migrations.AddField(
            model_name='hasta',
            name='nefrolitiazis',
            field=models.BooleanField(default=False, verbose_name='Nefrolitiazis'),
        ),
    ]
