# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta', '0023_auto_20160417_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyalizolayi',
            name='gecici_hasta',
            field=models.BooleanField(default=False, verbose_name='Geçici Hasta'),
        ),
    ]
