# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aylikveri'),
        ('gozlem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gozlem',
            name='merkez',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Merkez'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gozlem',
            name='gozlem_saati',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], verbose_name='Gözlem saati'),
        ),
        migrations.AlterField(
            model_name='gozlem',
            name='gozlem_suresi',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(5)], verbose_name='Gözlem süresi (dakika)'),
        ),
    ]
