# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gozlem.models


class Migration(migrations.Migration):

    dependencies = [
        ('gozlem', '0002_auto_20160420_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FistulDekanulasyonu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gozlenen', models.CharField(choices=[('d', 'Doktor'), ('h', 'Hemsire'), ('s', 'Diğer sağlık personeli')], max_length=1, verbose_name='Gözlenen')),
                ('ek_yorum', models.CharField(blank=True, max_length=100, verbose_name='Ek yorum')),
                ('ga01', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='El hijyeni uyguladı')),
                ('ga02', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Temiz eldiven giydi')),
                ('ga03', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Cihazdan aseptik olarak ayrıldı')),
                ('ga04', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='İğneler aseptik olarak ayrıldı')),
                ('ga05', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Fistül yerine baskı uygulamak için temiz eldiven giydi (personel veya hasta)')),
                ('ga06', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Fistül yerine temiz gazlı bez yerleştirildi')),
                ('ga07', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Eldiven çıkarıldı (personel)')),
                ('ga08', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='El hijyeni uygulandı (personel)')),
                ('ga09', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Eldiveni çıkardı ve el hijyeni uyguladı (hasta)')),
                ('gozlem', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gozlem.Gozlem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
