# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gozlem.models


class Migration(migrations.Migration):

    dependencies = [
        ('gozlem', '0003_fistuldekanulasyonu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElHijyeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gozlenen', models.CharField(choices=[('d', 'Doktor'), ('h', 'Hemsire'), ('s', 'Diğer sağlık personeli')], max_length=1, verbose_name='Gözlenen')),
                ('ek_yorum', models.CharField(blank=True, max_length=100, verbose_name='Ek yorum')),
                ('ga01', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta İle Temas Öncesi Yıkama')),
                ('ga02', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta İle Temas Öncesi Ovalama')),
                ('ga03', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Aseptik İşlemler Öncesi Yıkama')),
                ('ga04', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Aseptik İşlemler Öncesi Ovalama')),
                ('ga05', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Vücut Sıvılarının Bulaşma Riski Sonrası Yıkama')),
                ('ga06', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Vücut Sıvılarının Bulaşma Riski Sonrası Ovalama')),
                ('ga07', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta İle Temas Sonrası Yıkama')),
                ('ga08', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta İle Temas Sonrası Ovalama')),
                ('ga09', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta Çevresi İle Temas Sonrası Yıkama')),
                ('ga10', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Hasta Çevresi İle Temas Sonrası Ovalama')),
                ('gozlem', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gozlem.Gozlem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
