# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gozlem.models


class Migration(migrations.Migration):

    dependencies = [
        ('gozlem', '0004_elhijyeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='KateterBakimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gozlenen', models.CharField(choices=[('d', 'Doktor'), ('h', 'Hemsire'), ('s', 'Diğer sağlık personeli')], max_length=1, verbose_name='Gözlenen')),
                ('ek_yorum', models.CharField(blank=True, max_length=100, verbose_name='Ek yorum')),
                ('ga01', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Maske taktı')),
                ('ga02', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='El hijyeni uyguladı')),
                ('ga03', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Temiz eldiven giydi')),
                ('ga04', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Uygun şekilde cilt antiseptiği uyguladı')),
                ('ga05', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Antiseptiğin kurumasını bekledi')),
                ('ga06', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Antisepsi sonrası katetere temas etmedi')),
                ('ga07', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Antibiyotikli pomad uyguladı')),
                ('ga08', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Pansuman aseptik şekilde kapatıldı')),
                ('ga09', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='Eldiven çıkarıldı')),
                ('ga10', gozlem.models.GozlemAdimiField(choices=[('e', 'Evet'), ('h', 'Hayır'), ('b', 'Bilmiyorum')], default='b', max_length=1, verbose_name='El hijyeni uygulandı')),
                ('gozlem', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gozlem.Gozlem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
